document.write ("<p> El primer articulo es <strong>") ;
  document.write (articulos [0] + "</strong> </p>") ;	 
  document.write ("<p>El ultimo elemento es <strong>") ; 
    document.write (articulos[articulos.length-1] + "</strong> </p>") ;
    articulos.unshift ("Balón") ; 
    document.write ("<p> Casi se me olvida !!! Agregamos este elemento: <strong>") ;
      document.write (articulos[0] + "</strong> </p>") ;
      document.write ("<p> agregamos un elemento mas al final : <strong>");
        articulos.push (prompt("Intridcuce"));
        document.write (articulos [articulos.length-1] + "</strong> </p>");